# Interface entry port
server.port=9000

# Interface uniform prefix
spring.controller.path-prefix=/api

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha

knife4j.enable=true
knife4j.setting.language=zh_cn

logging.level.io.lettuce.core.protocol= error