package com.cz.entity;

import java.util.Date;

public class Camera {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column camera.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column camera.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column camera.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column camera.camera_loc
     *
     * @mbg.generated
     */
    private String cameraLoc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column camera.available
     *
     * @mbg.generated
     */
    private Boolean available;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column camera.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column camera.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column camera.deleted_at
     *
     * @mbg.generated
     */
    private Date deletedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column camera.id
     *
     * @return the value of camera.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column camera.id
     *
     * @param id the value for camera.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column camera.user_id
     *
     * @return the value of camera.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column camera.user_id
     *
     * @param userId the value for camera.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column camera.name
     *
     * @return the value of camera.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column camera.name
     *
     * @param name the value for camera.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column camera.camera_loc
     *
     * @return the value of camera.camera_loc
     *
     * @mbg.generated
     */
    public String getCameraLoc() {
        return cameraLoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column camera.camera_loc
     *
     * @param cameraLoc the value for camera.camera_loc
     *
     * @mbg.generated
     */
    public void setCameraLoc(String cameraLoc) {
        this.cameraLoc = cameraLoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column camera.available
     *
     * @return the value of camera.available
     *
     * @mbg.generated
     */
    public Boolean getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column camera.available
     *
     * @param available the value for camera.available
     *
     * @mbg.generated
     */
    public void setAvailable(Boolean available) {
        this.available = available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column camera.created_at
     *
     * @return the value of camera.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column camera.created_at
     *
     * @param createdAt the value for camera.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column camera.updated_at
     *
     * @return the value of camera.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column camera.updated_at
     *
     * @param updatedAt the value for camera.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column camera.deleted_at
     *
     * @return the value of camera.deleted_at
     *
     * @mbg.generated
     */
    public Date getDeletedAt() {
        return deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column camera.deleted_at
     *
     * @param deletedAt the value for camera.deleted_at
     *
     * @mbg.generated
     */
    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }
}