package com.cz.entity;

public class ChatConfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_config.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_config.marker
     *
     * @mbg.generated
     */
    private String marker;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_config.config_json
     *
     * @mbg.generated
     */
    private String configJson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_config.id
     *
     * @return the value of chat_config.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_config.id
     *
     * @param id the value for chat_config.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_config.marker
     *
     * @return the value of chat_config.marker
     *
     * @mbg.generated
     */
    public String getMarker() {
        return marker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_config.marker
     *
     * @param marker the value for chat_config.marker
     *
     * @mbg.generated
     */
    public void setMarker(String marker) {
        this.marker = marker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_config.config_json
     *
     * @return the value of chat_config.config_json
     *
     * @mbg.generated
     */
    public String getConfigJson() {
        return configJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_config.config_json
     *
     * @param configJson the value for chat_config.config_json
     *
     * @mbg.generated
     */
    public void setConfigJson(String configJson) {
        this.configJson = configJson;
    }
}