package com.cz.entity;

import java.util.Date;

public class ChatApiKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_api_key.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_api_key.platform
     *
     * @mbg.generated
     */
    private String platform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_api_key.model
     *
     * @mbg.generated
     */
    private String model;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_api_key.value
     *
     * @mbg.generated
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_api_key.last_used_at
     *
     * @mbg.generated
     */
    private Integer lastUsedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_api_key.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_api_key.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_api_key.deleted_at
     *
     * @mbg.generated
     */
    private Date deletedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_api_key.id
     *
     * @return the value of chat_api_key.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_api_key.id
     *
     * @param id the value for chat_api_key.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_api_key.platform
     *
     * @return the value of chat_api_key.platform
     *
     * @mbg.generated
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_api_key.platform
     *
     * @param platform the value for chat_api_key.platform
     *
     * @mbg.generated
     */
    public void setPlatform(String platform) {
        this.platform = platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_api_key.model
     *
     * @return the value of chat_api_key.model
     *
     * @mbg.generated
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_api_key.model
     *
     * @param model the value for chat_api_key.model
     *
     * @mbg.generated
     */
    public void setModel(String model) {
        this.model = model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_api_key.value
     *
     * @return the value of chat_api_key.value
     *
     * @mbg.generated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_api_key.value
     *
     * @param value the value for chat_api_key.value
     *
     * @mbg.generated
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_api_key.last_used_at
     *
     * @return the value of chat_api_key.last_used_at
     *
     * @mbg.generated
     */
    public Integer getLastUsedAt() {
        return lastUsedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_api_key.last_used_at
     *
     * @param lastUsedAt the value for chat_api_key.last_used_at
     *
     * @mbg.generated
     */
    public void setLastUsedAt(Integer lastUsedAt) {
        this.lastUsedAt = lastUsedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_api_key.created_at
     *
     * @return the value of chat_api_key.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_api_key.created_at
     *
     * @param createdAt the value for chat_api_key.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_api_key.updated_at
     *
     * @return the value of chat_api_key.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_api_key.updated_at
     *
     * @param updatedAt the value for chat_api_key.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_api_key.deleted_at
     *
     * @return the value of chat_api_key.deleted_at
     *
     * @mbg.generated
     */
    public Date getDeletedAt() {
        return deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_api_key.deleted_at
     *
     * @param deletedAt the value for chat_api_key.deleted_at
     *
     * @mbg.generated
     */
    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }
}