package com.cz.entity;

import java.util.Date;

public class ChatHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_history.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_history.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_history.chat_id
     *
     * @mbg.generated
     */
    private String chatId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_history.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_history.role_id
     *
     * @mbg.generated
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_history.tokens
     *
     * @mbg.generated
     */
    private Short tokens;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_history.use_context
     *
     * @mbg.generated
     */
    private Boolean useContext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_history.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_history.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_history.deleted_at
     *
     * @mbg.generated
     */
    private Date deletedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_history.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_history.id
     *
     * @return the value of chat_history.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_history.id
     *
     * @param id the value for chat_history.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_history.user_id
     *
     * @return the value of chat_history.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_history.user_id
     *
     * @param userId the value for chat_history.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_history.chat_id
     *
     * @return the value of chat_history.chat_id
     *
     * @mbg.generated
     */
    public String getChatId() {
        return chatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_history.chat_id
     *
     * @param chatId the value for chat_history.chat_id
     *
     * @mbg.generated
     */
    public void setChatId(String chatId) {
        this.chatId = chatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_history.type
     *
     * @return the value of chat_history.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_history.type
     *
     * @param type the value for chat_history.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_history.role_id
     *
     * @return the value of chat_history.role_id
     *
     * @mbg.generated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_history.role_id
     *
     * @param roleId the value for chat_history.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_history.tokens
     *
     * @return the value of chat_history.tokens
     *
     * @mbg.generated
     */
    public Short getTokens() {
        return tokens;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_history.tokens
     *
     * @param tokens the value for chat_history.tokens
     *
     * @mbg.generated
     */
    public void setTokens(Short tokens) {
        this.tokens = tokens;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_history.use_context
     *
     * @return the value of chat_history.use_context
     *
     * @mbg.generated
     */
    public Boolean getUseContext() {
        return useContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_history.use_context
     *
     * @param useContext the value for chat_history.use_context
     *
     * @mbg.generated
     */
    public void setUseContext(Boolean useContext) {
        this.useContext = useContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_history.created_at
     *
     * @return the value of chat_history.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_history.created_at
     *
     * @param createdAt the value for chat_history.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_history.updated_at
     *
     * @return the value of chat_history.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_history.updated_at
     *
     * @param updatedAt the value for chat_history.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_history.deleted_at
     *
     * @return the value of chat_history.deleted_at
     *
     * @mbg.generated
     */
    public Date getDeletedAt() {
        return deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_history.deleted_at
     *
     * @param deletedAt the value for chat_history.deleted_at
     *
     * @mbg.generated
     */
    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_history.content
     *
     * @return the value of chat_history.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_history.content
     *
     * @param content the value for chat_history.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }
}