package com.cz.entity;

import java.util.Date;

public class Event {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.event_status
     *
     * @mbg.generated
     */
    private Integer eventStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.event_type_id
     *
     * @mbg.generated
     */
    private Integer eventTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.event_type_content
     *
     * @mbg.generated
     */
    private String eventTypeContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.event_type_icon
     *
     * @mbg.generated
     */
    private String eventTypeIcon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.start_time
     *
     * @mbg.generated
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.end_time
     *
     * @mbg.generated
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.deleted_at
     *
     * @mbg.generated
     */
    private Date deletedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.id
     *
     * @return the value of event.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.id
     *
     * @param id the value for event.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.user_id
     *
     * @return the value of event.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.user_id
     *
     * @param userId the value for event.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.event_status
     *
     * @return the value of event.event_status
     *
     * @mbg.generated
     */
    public Integer getEventStatus() {
        return eventStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.event_status
     *
     * @param eventStatus the value for event.event_status
     *
     * @mbg.generated
     */
    public void setEventStatus(Integer eventStatus) {
        this.eventStatus = eventStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.event_type_id
     *
     * @return the value of event.event_type_id
     *
     * @mbg.generated
     */
    public Integer getEventTypeId() {
        return eventTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.event_type_id
     *
     * @param eventTypeId the value for event.event_type_id
     *
     * @mbg.generated
     */
    public void setEventTypeId(Integer eventTypeId) {
        this.eventTypeId = eventTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.event_type_content
     *
     * @return the value of event.event_type_content
     *
     * @mbg.generated
     */
    public String getEventTypeContent() {
        return eventTypeContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.event_type_content
     *
     * @param eventTypeContent the value for event.event_type_content
     *
     * @mbg.generated
     */
    public void setEventTypeContent(String eventTypeContent) {
        this.eventTypeContent = eventTypeContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.event_type_icon
     *
     * @return the value of event.event_type_icon
     *
     * @mbg.generated
     */
    public String getEventTypeIcon() {
        return eventTypeIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.event_type_icon
     *
     * @param eventTypeIcon the value for event.event_type_icon
     *
     * @mbg.generated
     */
    public void setEventTypeIcon(String eventTypeIcon) {
        this.eventTypeIcon = eventTypeIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.title
     *
     * @return the value of event.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.title
     *
     * @param title the value for event.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.description
     *
     * @return the value of event.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.description
     *
     * @param description the value for event.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.start_time
     *
     * @return the value of event.start_time
     *
     * @mbg.generated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.start_time
     *
     * @param startTime the value for event.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.end_time
     *
     * @return the value of event.end_time
     *
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.end_time
     *
     * @param endTime the value for event.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.created_at
     *
     * @return the value of event.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.created_at
     *
     * @param createdAt the value for event.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.updated_at
     *
     * @return the value of event.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.updated_at
     *
     * @param updatedAt the value for event.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.deleted_at
     *
     * @return the value of event.deleted_at
     *
     * @mbg.generated
     */
    public Date getDeletedAt() {
        return deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.deleted_at
     *
     * @param deletedAt the value for event.deleted_at
     *
     * @mbg.generated
     */
    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }
}