package com.cz.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MeasurementExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table measurement
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table measurement
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table measurement
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measurement
     *
     * @mbg.generated
     */
    public MeasurementExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measurement
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measurement
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measurement
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measurement
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measurement
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measurement
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measurement
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measurement
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measurement
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measurement
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table measurement
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andSystolicBpIsNull() {
            addCriterion("systolic_bp is null");
            return (Criteria) this;
        }

        public Criteria andSystolicBpIsNotNull() {
            addCriterion("systolic_bp is not null");
            return (Criteria) this;
        }

        public Criteria andSystolicBpEqualTo(Integer value) {
            addCriterion("systolic_bp =", value, "systolicBp");
            return (Criteria) this;
        }

        public Criteria andSystolicBpNotEqualTo(Integer value) {
            addCriterion("systolic_bp <>", value, "systolicBp");
            return (Criteria) this;
        }

        public Criteria andSystolicBpGreaterThan(Integer value) {
            addCriterion("systolic_bp >", value, "systolicBp");
            return (Criteria) this;
        }

        public Criteria andSystolicBpGreaterThanOrEqualTo(Integer value) {
            addCriterion("systolic_bp >=", value, "systolicBp");
            return (Criteria) this;
        }

        public Criteria andSystolicBpLessThan(Integer value) {
            addCriterion("systolic_bp <", value, "systolicBp");
            return (Criteria) this;
        }

        public Criteria andSystolicBpLessThanOrEqualTo(Integer value) {
            addCriterion("systolic_bp <=", value, "systolicBp");
            return (Criteria) this;
        }

        public Criteria andSystolicBpIn(List<Integer> values) {
            addCriterion("systolic_bp in", values, "systolicBp");
            return (Criteria) this;
        }

        public Criteria andSystolicBpNotIn(List<Integer> values) {
            addCriterion("systolic_bp not in", values, "systolicBp");
            return (Criteria) this;
        }

        public Criteria andSystolicBpBetween(Integer value1, Integer value2) {
            addCriterion("systolic_bp between", value1, value2, "systolicBp");
            return (Criteria) this;
        }

        public Criteria andSystolicBpNotBetween(Integer value1, Integer value2) {
            addCriterion("systolic_bp not between", value1, value2, "systolicBp");
            return (Criteria) this;
        }

        public Criteria andDiastolicBpIsNull() {
            addCriterion("diastolic_bp is null");
            return (Criteria) this;
        }

        public Criteria andDiastolicBpIsNotNull() {
            addCriterion("diastolic_bp is not null");
            return (Criteria) this;
        }

        public Criteria andDiastolicBpEqualTo(Integer value) {
            addCriterion("diastolic_bp =", value, "diastolicBp");
            return (Criteria) this;
        }

        public Criteria andDiastolicBpNotEqualTo(Integer value) {
            addCriterion("diastolic_bp <>", value, "diastolicBp");
            return (Criteria) this;
        }

        public Criteria andDiastolicBpGreaterThan(Integer value) {
            addCriterion("diastolic_bp >", value, "diastolicBp");
            return (Criteria) this;
        }

        public Criteria andDiastolicBpGreaterThanOrEqualTo(Integer value) {
            addCriterion("diastolic_bp >=", value, "diastolicBp");
            return (Criteria) this;
        }

        public Criteria andDiastolicBpLessThan(Integer value) {
            addCriterion("diastolic_bp <", value, "diastolicBp");
            return (Criteria) this;
        }

        public Criteria andDiastolicBpLessThanOrEqualTo(Integer value) {
            addCriterion("diastolic_bp <=", value, "diastolicBp");
            return (Criteria) this;
        }

        public Criteria andDiastolicBpIn(List<Integer> values) {
            addCriterion("diastolic_bp in", values, "diastolicBp");
            return (Criteria) this;
        }

        public Criteria andDiastolicBpNotIn(List<Integer> values) {
            addCriterion("diastolic_bp not in", values, "diastolicBp");
            return (Criteria) this;
        }

        public Criteria andDiastolicBpBetween(Integer value1, Integer value2) {
            addCriterion("diastolic_bp between", value1, value2, "diastolicBp");
            return (Criteria) this;
        }

        public Criteria andDiastolicBpNotBetween(Integer value1, Integer value2) {
            addCriterion("diastolic_bp not between", value1, value2, "diastolicBp");
            return (Criteria) this;
        }

        public Criteria andTemperatureIsNull() {
            addCriterion("temperature is null");
            return (Criteria) this;
        }

        public Criteria andTemperatureIsNotNull() {
            addCriterion("temperature is not null");
            return (Criteria) this;
        }

        public Criteria andTemperatureEqualTo(Integer value) {
            addCriterion("temperature =", value, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureNotEqualTo(Integer value) {
            addCriterion("temperature <>", value, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureGreaterThan(Integer value) {
            addCriterion("temperature >", value, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureGreaterThanOrEqualTo(Integer value) {
            addCriterion("temperature >=", value, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureLessThan(Integer value) {
            addCriterion("temperature <", value, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureLessThanOrEqualTo(Integer value) {
            addCriterion("temperature <=", value, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureIn(List<Integer> values) {
            addCriterion("temperature in", values, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureNotIn(List<Integer> values) {
            addCriterion("temperature not in", values, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureBetween(Integer value1, Integer value2) {
            addCriterion("temperature between", value1, value2, "temperature");
            return (Criteria) this;
        }

        public Criteria andTemperatureNotBetween(Integer value1, Integer value2) {
            addCriterion("temperature not between", value1, value2, "temperature");
            return (Criteria) this;
        }

        public Criteria andHeartRateIsNull() {
            addCriterion("heart_rate is null");
            return (Criteria) this;
        }

        public Criteria andHeartRateIsNotNull() {
            addCriterion("heart_rate is not null");
            return (Criteria) this;
        }

        public Criteria andHeartRateEqualTo(Integer value) {
            addCriterion("heart_rate =", value, "heartRate");
            return (Criteria) this;
        }

        public Criteria andHeartRateNotEqualTo(Integer value) {
            addCriterion("heart_rate <>", value, "heartRate");
            return (Criteria) this;
        }

        public Criteria andHeartRateGreaterThan(Integer value) {
            addCriterion("heart_rate >", value, "heartRate");
            return (Criteria) this;
        }

        public Criteria andHeartRateGreaterThanOrEqualTo(Integer value) {
            addCriterion("heart_rate >=", value, "heartRate");
            return (Criteria) this;
        }

        public Criteria andHeartRateLessThan(Integer value) {
            addCriterion("heart_rate <", value, "heartRate");
            return (Criteria) this;
        }

        public Criteria andHeartRateLessThanOrEqualTo(Integer value) {
            addCriterion("heart_rate <=", value, "heartRate");
            return (Criteria) this;
        }

        public Criteria andHeartRateIn(List<Integer> values) {
            addCriterion("heart_rate in", values, "heartRate");
            return (Criteria) this;
        }

        public Criteria andHeartRateNotIn(List<Integer> values) {
            addCriterion("heart_rate not in", values, "heartRate");
            return (Criteria) this;
        }

        public Criteria andHeartRateBetween(Integer value1, Integer value2) {
            addCriterion("heart_rate between", value1, value2, "heartRate");
            return (Criteria) this;
        }

        public Criteria andHeartRateNotBetween(Integer value1, Integer value2) {
            addCriterion("heart_rate not between", value1, value2, "heartRate");
            return (Criteria) this;
        }

        public Criteria andOxygenSaturationIsNull() {
            addCriterion("oxygen_saturation is null");
            return (Criteria) this;
        }

        public Criteria andOxygenSaturationIsNotNull() {
            addCriterion("oxygen_saturation is not null");
            return (Criteria) this;
        }

        public Criteria andOxygenSaturationEqualTo(Integer value) {
            addCriterion("oxygen_saturation =", value, "oxygenSaturation");
            return (Criteria) this;
        }

        public Criteria andOxygenSaturationNotEqualTo(Integer value) {
            addCriterion("oxygen_saturation <>", value, "oxygenSaturation");
            return (Criteria) this;
        }

        public Criteria andOxygenSaturationGreaterThan(Integer value) {
            addCriterion("oxygen_saturation >", value, "oxygenSaturation");
            return (Criteria) this;
        }

        public Criteria andOxygenSaturationGreaterThanOrEqualTo(Integer value) {
            addCriterion("oxygen_saturation >=", value, "oxygenSaturation");
            return (Criteria) this;
        }

        public Criteria andOxygenSaturationLessThan(Integer value) {
            addCriterion("oxygen_saturation <", value, "oxygenSaturation");
            return (Criteria) this;
        }

        public Criteria andOxygenSaturationLessThanOrEqualTo(Integer value) {
            addCriterion("oxygen_saturation <=", value, "oxygenSaturation");
            return (Criteria) this;
        }

        public Criteria andOxygenSaturationIn(List<Integer> values) {
            addCriterion("oxygen_saturation in", values, "oxygenSaturation");
            return (Criteria) this;
        }

        public Criteria andOxygenSaturationNotIn(List<Integer> values) {
            addCriterion("oxygen_saturation not in", values, "oxygenSaturation");
            return (Criteria) this;
        }

        public Criteria andOxygenSaturationBetween(Integer value1, Integer value2) {
            addCriterion("oxygen_saturation between", value1, value2, "oxygenSaturation");
            return (Criteria) this;
        }

        public Criteria andOxygenSaturationNotBetween(Integer value1, Integer value2) {
            addCriterion("oxygen_saturation not between", value1, value2, "oxygenSaturation");
            return (Criteria) this;
        }

        public Criteria andRespiratoryRateIsNull() {
            addCriterion("respiratory_rate is null");
            return (Criteria) this;
        }

        public Criteria andRespiratoryRateIsNotNull() {
            addCriterion("respiratory_rate is not null");
            return (Criteria) this;
        }

        public Criteria andRespiratoryRateEqualTo(Integer value) {
            addCriterion("respiratory_rate =", value, "respiratoryRate");
            return (Criteria) this;
        }

        public Criteria andRespiratoryRateNotEqualTo(Integer value) {
            addCriterion("respiratory_rate <>", value, "respiratoryRate");
            return (Criteria) this;
        }

        public Criteria andRespiratoryRateGreaterThan(Integer value) {
            addCriterion("respiratory_rate >", value, "respiratoryRate");
            return (Criteria) this;
        }

        public Criteria andRespiratoryRateGreaterThanOrEqualTo(Integer value) {
            addCriterion("respiratory_rate >=", value, "respiratoryRate");
            return (Criteria) this;
        }

        public Criteria andRespiratoryRateLessThan(Integer value) {
            addCriterion("respiratory_rate <", value, "respiratoryRate");
            return (Criteria) this;
        }

        public Criteria andRespiratoryRateLessThanOrEqualTo(Integer value) {
            addCriterion("respiratory_rate <=", value, "respiratoryRate");
            return (Criteria) this;
        }

        public Criteria andRespiratoryRateIn(List<Integer> values) {
            addCriterion("respiratory_rate in", values, "respiratoryRate");
            return (Criteria) this;
        }

        public Criteria andRespiratoryRateNotIn(List<Integer> values) {
            addCriterion("respiratory_rate not in", values, "respiratoryRate");
            return (Criteria) this;
        }

        public Criteria andRespiratoryRateBetween(Integer value1, Integer value2) {
            addCriterion("respiratory_rate between", value1, value2, "respiratoryRate");
            return (Criteria) this;
        }

        public Criteria andRespiratoryRateNotBetween(Integer value1, Integer value2) {
            addCriterion("respiratory_rate not between", value1, value2, "respiratoryRate");
            return (Criteria) this;
        }

        public Criteria andMeasurementTimeIsNull() {
            addCriterion("measurement_time is null");
            return (Criteria) this;
        }

        public Criteria andMeasurementTimeIsNotNull() {
            addCriterion("measurement_time is not null");
            return (Criteria) this;
        }

        public Criteria andMeasurementTimeEqualTo(Date value) {
            addCriterion("measurement_time =", value, "measurementTime");
            return (Criteria) this;
        }

        public Criteria andMeasurementTimeNotEqualTo(Date value) {
            addCriterion("measurement_time <>", value, "measurementTime");
            return (Criteria) this;
        }

        public Criteria andMeasurementTimeGreaterThan(Date value) {
            addCriterion("measurement_time >", value, "measurementTime");
            return (Criteria) this;
        }

        public Criteria andMeasurementTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("measurement_time >=", value, "measurementTime");
            return (Criteria) this;
        }

        public Criteria andMeasurementTimeLessThan(Date value) {
            addCriterion("measurement_time <", value, "measurementTime");
            return (Criteria) this;
        }

        public Criteria andMeasurementTimeLessThanOrEqualTo(Date value) {
            addCriterion("measurement_time <=", value, "measurementTime");
            return (Criteria) this;
        }

        public Criteria andMeasurementTimeIn(List<Date> values) {
            addCriterion("measurement_time in", values, "measurementTime");
            return (Criteria) this;
        }

        public Criteria andMeasurementTimeNotIn(List<Date> values) {
            addCriterion("measurement_time not in", values, "measurementTime");
            return (Criteria) this;
        }

        public Criteria andMeasurementTimeBetween(Date value1, Date value2) {
            addCriterion("measurement_time between", value1, value2, "measurementTime");
            return (Criteria) this;
        }

        public Criteria andMeasurementTimeNotBetween(Date value1, Date value2) {
            addCriterion("measurement_time not between", value1, value2, "measurementTime");
            return (Criteria) this;
        }

        public Criteria andStepsIsNull() {
            addCriterion("steps is null");
            return (Criteria) this;
        }

        public Criteria andStepsIsNotNull() {
            addCriterion("steps is not null");
            return (Criteria) this;
        }

        public Criteria andStepsEqualTo(Integer value) {
            addCriterion("steps =", value, "steps");
            return (Criteria) this;
        }

        public Criteria andStepsNotEqualTo(Integer value) {
            addCriterion("steps <>", value, "steps");
            return (Criteria) this;
        }

        public Criteria andStepsGreaterThan(Integer value) {
            addCriterion("steps >", value, "steps");
            return (Criteria) this;
        }

        public Criteria andStepsGreaterThanOrEqualTo(Integer value) {
            addCriterion("steps >=", value, "steps");
            return (Criteria) this;
        }

        public Criteria andStepsLessThan(Integer value) {
            addCriterion("steps <", value, "steps");
            return (Criteria) this;
        }

        public Criteria andStepsLessThanOrEqualTo(Integer value) {
            addCriterion("steps <=", value, "steps");
            return (Criteria) this;
        }

        public Criteria andStepsIn(List<Integer> values) {
            addCriterion("steps in", values, "steps");
            return (Criteria) this;
        }

        public Criteria andStepsNotIn(List<Integer> values) {
            addCriterion("steps not in", values, "steps");
            return (Criteria) this;
        }

        public Criteria andStepsBetween(Integer value1, Integer value2) {
            addCriterion("steps between", value1, value2, "steps");
            return (Criteria) this;
        }

        public Criteria andStepsNotBetween(Integer value1, Integer value2) {
            addCriterion("steps not between", value1, value2, "steps");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(Date value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(Date value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(Date value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(Date value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<Date> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<Date> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(Date value1, Date value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNull() {
            addCriterion("updated_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNotNull() {
            addCriterion("updated_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtEqualTo(Date value) {
            addCriterion("updated_at =", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotEqualTo(Date value) {
            addCriterion("updated_at <>", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThan(Date value) {
            addCriterion("updated_at >", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("updated_at >=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThan(Date value) {
            addCriterion("updated_at <", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
            addCriterion("updated_at <=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIn(List<Date> values) {
            addCriterion("updated_at in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotIn(List<Date> values) {
            addCriterion("updated_at not in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtBetween(Date value1, Date value2) {
            addCriterion("updated_at between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
            addCriterion("updated_at not between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andDeletedAtIsNull() {
            addCriterion("deleted_at is null");
            return (Criteria) this;
        }

        public Criteria andDeletedAtIsNotNull() {
            addCriterion("deleted_at is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedAtEqualTo(Date value) {
            addCriterion("deleted_at =", value, "deletedAt");
            return (Criteria) this;
        }

        public Criteria andDeletedAtNotEqualTo(Date value) {
            addCriterion("deleted_at <>", value, "deletedAt");
            return (Criteria) this;
        }

        public Criteria andDeletedAtGreaterThan(Date value) {
            addCriterion("deleted_at >", value, "deletedAt");
            return (Criteria) this;
        }

        public Criteria andDeletedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("deleted_at >=", value, "deletedAt");
            return (Criteria) this;
        }

        public Criteria andDeletedAtLessThan(Date value) {
            addCriterion("deleted_at <", value, "deletedAt");
            return (Criteria) this;
        }

        public Criteria andDeletedAtLessThanOrEqualTo(Date value) {
            addCriterion("deleted_at <=", value, "deletedAt");
            return (Criteria) this;
        }

        public Criteria andDeletedAtIn(List<Date> values) {
            addCriterion("deleted_at in", values, "deletedAt");
            return (Criteria) this;
        }

        public Criteria andDeletedAtNotIn(List<Date> values) {
            addCriterion("deleted_at not in", values, "deletedAt");
            return (Criteria) this;
        }

        public Criteria andDeletedAtBetween(Date value1, Date value2) {
            addCriterion("deleted_at between", value1, value2, "deletedAt");
            return (Criteria) this;
        }

        public Criteria andDeletedAtNotBetween(Date value1, Date value2) {
            addCriterion("deleted_at not between", value1, value2, "deletedAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table measurement
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table measurement
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}