package com.cz.entity;

import java.util.Date;

public class Measurement {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column measurement.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column measurement.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column measurement.systolic_bp
     *
     * @mbg.generated
     */
    private Integer systolicBp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column measurement.diastolic_bp
     *
     * @mbg.generated
     */
    private Integer diastolicBp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column measurement.temperature
     *
     * @mbg.generated
     */
    private Integer temperature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column measurement.heart_rate
     *
     * @mbg.generated
     */
    private Integer heartRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column measurement.oxygen_saturation
     *
     * @mbg.generated
     */
    private Integer oxygenSaturation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column measurement.respiratory_rate
     *
     * @mbg.generated
     */
    private Integer respiratoryRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column measurement.measurement_time
     *
     * @mbg.generated
     */
    private Date measurementTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column measurement.steps
     *
     * @mbg.generated
     */
    private Integer steps;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column measurement.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column measurement.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column measurement.deleted_at
     *
     * @mbg.generated
     */
    private Date deletedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column measurement.notes
     *
     * @mbg.generated
     */
    private String notes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column measurement.id
     *
     * @return the value of measurement.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column measurement.id
     *
     * @param id the value for measurement.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column measurement.user_id
     *
     * @return the value of measurement.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column measurement.user_id
     *
     * @param userId the value for measurement.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column measurement.systolic_bp
     *
     * @return the value of measurement.systolic_bp
     *
     * @mbg.generated
     */
    public Integer getSystolicBp() {
        return systolicBp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column measurement.systolic_bp
     *
     * @param systolicBp the value for measurement.systolic_bp
     *
     * @mbg.generated
     */
    public void setSystolicBp(Integer systolicBp) {
        this.systolicBp = systolicBp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column measurement.diastolic_bp
     *
     * @return the value of measurement.diastolic_bp
     *
     * @mbg.generated
     */
    public Integer getDiastolicBp() {
        return diastolicBp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column measurement.diastolic_bp
     *
     * @param diastolicBp the value for measurement.diastolic_bp
     *
     * @mbg.generated
     */
    public void setDiastolicBp(Integer diastolicBp) {
        this.diastolicBp = diastolicBp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column measurement.temperature
     *
     * @return the value of measurement.temperature
     *
     * @mbg.generated
     */
    public Integer getTemperature() {
        return temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column measurement.temperature
     *
     * @param temperature the value for measurement.temperature
     *
     * @mbg.generated
     */
    public void setTemperature(Integer temperature) {
        this.temperature = temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column measurement.heart_rate
     *
     * @return the value of measurement.heart_rate
     *
     * @mbg.generated
     */
    public Integer getHeartRate() {
        return heartRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column measurement.heart_rate
     *
     * @param heartRate the value for measurement.heart_rate
     *
     * @mbg.generated
     */
    public void setHeartRate(Integer heartRate) {
        this.heartRate = heartRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column measurement.oxygen_saturation
     *
     * @return the value of measurement.oxygen_saturation
     *
     * @mbg.generated
     */
    public Integer getOxygenSaturation() {
        return oxygenSaturation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column measurement.oxygen_saturation
     *
     * @param oxygenSaturation the value for measurement.oxygen_saturation
     *
     * @mbg.generated
     */
    public void setOxygenSaturation(Integer oxygenSaturation) {
        this.oxygenSaturation = oxygenSaturation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column measurement.respiratory_rate
     *
     * @return the value of measurement.respiratory_rate
     *
     * @mbg.generated
     */
    public Integer getRespiratoryRate() {
        return respiratoryRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column measurement.respiratory_rate
     *
     * @param respiratoryRate the value for measurement.respiratory_rate
     *
     * @mbg.generated
     */
    public void setRespiratoryRate(Integer respiratoryRate) {
        this.respiratoryRate = respiratoryRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column measurement.measurement_time
     *
     * @return the value of measurement.measurement_time
     *
     * @mbg.generated
     */
    public Date getMeasurementTime() {
        return measurementTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column measurement.measurement_time
     *
     * @param measurementTime the value for measurement.measurement_time
     *
     * @mbg.generated
     */
    public void setMeasurementTime(Date measurementTime) {
        this.measurementTime = measurementTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column measurement.steps
     *
     * @return the value of measurement.steps
     *
     * @mbg.generated
     */
    public Integer getSteps() {
        return steps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column measurement.steps
     *
     * @param steps the value for measurement.steps
     *
     * @mbg.generated
     */
    public void setSteps(Integer steps) {
        this.steps = steps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column measurement.created_at
     *
     * @return the value of measurement.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column measurement.created_at
     *
     * @param createdAt the value for measurement.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column measurement.updated_at
     *
     * @return the value of measurement.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column measurement.updated_at
     *
     * @param updatedAt the value for measurement.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column measurement.deleted_at
     *
     * @return the value of measurement.deleted_at
     *
     * @mbg.generated
     */
    public Date getDeletedAt() {
        return deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column measurement.deleted_at
     *
     * @param deletedAt the value for measurement.deleted_at
     *
     * @mbg.generated
     */
    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column measurement.notes
     *
     * @return the value of measurement.notes
     *
     * @mbg.generated
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column measurement.notes
     *
     * @param notes the value for measurement.notes
     *
     * @mbg.generated
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }
}