package com.cz.entity;

import java.util.Date;

public class Posture {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posture.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posture.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posture.fall_down_status
     *
     * @mbg.generated
     */
    private Integer fallDownStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posture.fall_down_time
     *
     * @mbg.generated
     */
    private Date fallDownTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posture.fall_down_reply
     *
     * @mbg.generated
     */
    private Integer fallDownReply;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posture.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posture.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posture.deleted_at
     *
     * @mbg.generated
     */
    private Date deletedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posture.id
     *
     * @return the value of posture.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posture.id
     *
     * @param id the value for posture.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posture.user_id
     *
     * @return the value of posture.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posture.user_id
     *
     * @param userId the value for posture.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posture.fall_down_status
     *
     * @return the value of posture.fall_down_status
     *
     * @mbg.generated
     */
    public Integer getFallDownStatus() {
        return fallDownStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posture.fall_down_status
     *
     * @param fallDownStatus the value for posture.fall_down_status
     *
     * @mbg.generated
     */
    public void setFallDownStatus(Integer fallDownStatus) {
        this.fallDownStatus = fallDownStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posture.fall_down_time
     *
     * @return the value of posture.fall_down_time
     *
     * @mbg.generated
     */
    public Date getFallDownTime() {
        return fallDownTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posture.fall_down_time
     *
     * @param fallDownTime the value for posture.fall_down_time
     *
     * @mbg.generated
     */
    public void setFallDownTime(Date fallDownTime) {
        this.fallDownTime = fallDownTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posture.fall_down_reply
     *
     * @return the value of posture.fall_down_reply
     *
     * @mbg.generated
     */
    public Integer getFallDownReply() {
        return fallDownReply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posture.fall_down_reply
     *
     * @param fallDownReply the value for posture.fall_down_reply
     *
     * @mbg.generated
     */
    public void setFallDownReply(Integer fallDownReply) {
        this.fallDownReply = fallDownReply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posture.created_at
     *
     * @return the value of posture.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posture.created_at
     *
     * @param createdAt the value for posture.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posture.updated_at
     *
     * @return the value of posture.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posture.updated_at
     *
     * @param updatedAt the value for posture.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posture.deleted_at
     *
     * @return the value of posture.deleted_at
     *
     * @mbg.generated
     */
    public Date getDeletedAt() {
        return deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posture.deleted_at
     *
     * @param deletedAt the value for posture.deleted_at
     *
     * @mbg.generated
     */
    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }
}