package com.cz.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SleepExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sleep
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sleep
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sleep
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sleep
     *
     * @mbg.generated
     */
    public SleepExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sleep
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sleep
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sleep
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sleep
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sleep
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sleep
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sleep
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sleep
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sleep
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sleep
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sleep
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andExistIsNull() {
            addCriterion("exist is null");
            return (Criteria) this;
        }

        public Criteria andExistIsNotNull() {
            addCriterion("exist is not null");
            return (Criteria) this;
        }

        public Criteria andExistEqualTo(Integer value) {
            addCriterion("exist =", value, "exist");
            return (Criteria) this;
        }

        public Criteria andExistNotEqualTo(Integer value) {
            addCriterion("exist <>", value, "exist");
            return (Criteria) this;
        }

        public Criteria andExistGreaterThan(Integer value) {
            addCriterion("exist >", value, "exist");
            return (Criteria) this;
        }

        public Criteria andExistGreaterThanOrEqualTo(Integer value) {
            addCriterion("exist >=", value, "exist");
            return (Criteria) this;
        }

        public Criteria andExistLessThan(Integer value) {
            addCriterion("exist <", value, "exist");
            return (Criteria) this;
        }

        public Criteria andExistLessThanOrEqualTo(Integer value) {
            addCriterion("exist <=", value, "exist");
            return (Criteria) this;
        }

        public Criteria andExistIn(List<Integer> values) {
            addCriterion("exist in", values, "exist");
            return (Criteria) this;
        }

        public Criteria andExistNotIn(List<Integer> values) {
            addCriterion("exist not in", values, "exist");
            return (Criteria) this;
        }

        public Criteria andExistBetween(Integer value1, Integer value2) {
            addCriterion("exist between", value1, value2, "exist");
            return (Criteria) this;
        }

        public Criteria andExistNotBetween(Integer value1, Integer value2) {
            addCriterion("exist not between", value1, value2, "exist");
            return (Criteria) this;
        }

        public Criteria andSleepStatusIsNull() {
            addCriterion("sleep_status is null");
            return (Criteria) this;
        }

        public Criteria andSleepStatusIsNotNull() {
            addCriterion("sleep_status is not null");
            return (Criteria) this;
        }

        public Criteria andSleepStatusEqualTo(Integer value) {
            addCriterion("sleep_status =", value, "sleepStatus");
            return (Criteria) this;
        }

        public Criteria andSleepStatusNotEqualTo(Integer value) {
            addCriterion("sleep_status <>", value, "sleepStatus");
            return (Criteria) this;
        }

        public Criteria andSleepStatusGreaterThan(Integer value) {
            addCriterion("sleep_status >", value, "sleepStatus");
            return (Criteria) this;
        }

        public Criteria andSleepStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("sleep_status >=", value, "sleepStatus");
            return (Criteria) this;
        }

        public Criteria andSleepStatusLessThan(Integer value) {
            addCriterion("sleep_status <", value, "sleepStatus");
            return (Criteria) this;
        }

        public Criteria andSleepStatusLessThanOrEqualTo(Integer value) {
            addCriterion("sleep_status <=", value, "sleepStatus");
            return (Criteria) this;
        }

        public Criteria andSleepStatusIn(List<Integer> values) {
            addCriterion("sleep_status in", values, "sleepStatus");
            return (Criteria) this;
        }

        public Criteria andSleepStatusNotIn(List<Integer> values) {
            addCriterion("sleep_status not in", values, "sleepStatus");
            return (Criteria) this;
        }

        public Criteria andSleepStatusBetween(Integer value1, Integer value2) {
            addCriterion("sleep_status between", value1, value2, "sleepStatus");
            return (Criteria) this;
        }

        public Criteria andSleepStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("sleep_status not between", value1, value2, "sleepStatus");
            return (Criteria) this;
        }

        public Criteria andSleepScoreIsNull() {
            addCriterion("sleep_score is null");
            return (Criteria) this;
        }

        public Criteria andSleepScoreIsNotNull() {
            addCriterion("sleep_score is not null");
            return (Criteria) this;
        }

        public Criteria andSleepScoreEqualTo(Integer value) {
            addCriterion("sleep_score =", value, "sleepScore");
            return (Criteria) this;
        }

        public Criteria andSleepScoreNotEqualTo(Integer value) {
            addCriterion("sleep_score <>", value, "sleepScore");
            return (Criteria) this;
        }

        public Criteria andSleepScoreGreaterThan(Integer value) {
            addCriterion("sleep_score >", value, "sleepScore");
            return (Criteria) this;
        }

        public Criteria andSleepScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("sleep_score >=", value, "sleepScore");
            return (Criteria) this;
        }

        public Criteria andSleepScoreLessThan(Integer value) {
            addCriterion("sleep_score <", value, "sleepScore");
            return (Criteria) this;
        }

        public Criteria andSleepScoreLessThanOrEqualTo(Integer value) {
            addCriterion("sleep_score <=", value, "sleepScore");
            return (Criteria) this;
        }

        public Criteria andSleepScoreIn(List<Integer> values) {
            addCriterion("sleep_score in", values, "sleepScore");
            return (Criteria) this;
        }

        public Criteria andSleepScoreNotIn(List<Integer> values) {
            addCriterion("sleep_score not in", values, "sleepScore");
            return (Criteria) this;
        }

        public Criteria andSleepScoreBetween(Integer value1, Integer value2) {
            addCriterion("sleep_score between", value1, value2, "sleepScore");
            return (Criteria) this;
        }

        public Criteria andSleepScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("sleep_score not between", value1, value2, "sleepScore");
            return (Criteria) this;
        }

        public Criteria andSleepQualityIsNull() {
            addCriterion("sleep_quality is null");
            return (Criteria) this;
        }

        public Criteria andSleepQualityIsNotNull() {
            addCriterion("sleep_quality is not null");
            return (Criteria) this;
        }

        public Criteria andSleepQualityEqualTo(Integer value) {
            addCriterion("sleep_quality =", value, "sleepQuality");
            return (Criteria) this;
        }

        public Criteria andSleepQualityNotEqualTo(Integer value) {
            addCriterion("sleep_quality <>", value, "sleepQuality");
            return (Criteria) this;
        }

        public Criteria andSleepQualityGreaterThan(Integer value) {
            addCriterion("sleep_quality >", value, "sleepQuality");
            return (Criteria) this;
        }

        public Criteria andSleepQualityGreaterThanOrEqualTo(Integer value) {
            addCriterion("sleep_quality >=", value, "sleepQuality");
            return (Criteria) this;
        }

        public Criteria andSleepQualityLessThan(Integer value) {
            addCriterion("sleep_quality <", value, "sleepQuality");
            return (Criteria) this;
        }

        public Criteria andSleepQualityLessThanOrEqualTo(Integer value) {
            addCriterion("sleep_quality <=", value, "sleepQuality");
            return (Criteria) this;
        }

        public Criteria andSleepQualityIn(List<Integer> values) {
            addCriterion("sleep_quality in", values, "sleepQuality");
            return (Criteria) this;
        }

        public Criteria andSleepQualityNotIn(List<Integer> values) {
            addCriterion("sleep_quality not in", values, "sleepQuality");
            return (Criteria) this;
        }

        public Criteria andSleepQualityBetween(Integer value1, Integer value2) {
            addCriterion("sleep_quality between", value1, value2, "sleepQuality");
            return (Criteria) this;
        }

        public Criteria andSleepQualityNotBetween(Integer value1, Integer value2) {
            addCriterion("sleep_quality not between", value1, value2, "sleepQuality");
            return (Criteria) this;
        }

        public Criteria andTotalSleepDurationIsNull() {
            addCriterion("total_sleep_duration is null");
            return (Criteria) this;
        }

        public Criteria andTotalSleepDurationIsNotNull() {
            addCriterion("total_sleep_duration is not null");
            return (Criteria) this;
        }

        public Criteria andTotalSleepDurationEqualTo(Integer value) {
            addCriterion("total_sleep_duration =", value, "totalSleepDuration");
            return (Criteria) this;
        }

        public Criteria andTotalSleepDurationNotEqualTo(Integer value) {
            addCriterion("total_sleep_duration <>", value, "totalSleepDuration");
            return (Criteria) this;
        }

        public Criteria andTotalSleepDurationGreaterThan(Integer value) {
            addCriterion("total_sleep_duration >", value, "totalSleepDuration");
            return (Criteria) this;
        }

        public Criteria andTotalSleepDurationGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_sleep_duration >=", value, "totalSleepDuration");
            return (Criteria) this;
        }

        public Criteria andTotalSleepDurationLessThan(Integer value) {
            addCriterion("total_sleep_duration <", value, "totalSleepDuration");
            return (Criteria) this;
        }

        public Criteria andTotalSleepDurationLessThanOrEqualTo(Integer value) {
            addCriterion("total_sleep_duration <=", value, "totalSleepDuration");
            return (Criteria) this;
        }

        public Criteria andTotalSleepDurationIn(List<Integer> values) {
            addCriterion("total_sleep_duration in", values, "totalSleepDuration");
            return (Criteria) this;
        }

        public Criteria andTotalSleepDurationNotIn(List<Integer> values) {
            addCriterion("total_sleep_duration not in", values, "totalSleepDuration");
            return (Criteria) this;
        }

        public Criteria andTotalSleepDurationBetween(Integer value1, Integer value2) {
            addCriterion("total_sleep_duration between", value1, value2, "totalSleepDuration");
            return (Criteria) this;
        }

        public Criteria andTotalSleepDurationNotBetween(Integer value1, Integer value2) {
            addCriterion("total_sleep_duration not between", value1, value2, "totalSleepDuration");
            return (Criteria) this;
        }

        public Criteria andMeanSleepRespirationIsNull() {
            addCriterion("mean_sleep_respiration is null");
            return (Criteria) this;
        }

        public Criteria andMeanSleepRespirationIsNotNull() {
            addCriterion("mean_sleep_respiration is not null");
            return (Criteria) this;
        }

        public Criteria andMeanSleepRespirationEqualTo(Integer value) {
            addCriterion("mean_sleep_respiration =", value, "meanSleepRespiration");
            return (Criteria) this;
        }

        public Criteria andMeanSleepRespirationNotEqualTo(Integer value) {
            addCriterion("mean_sleep_respiration <>", value, "meanSleepRespiration");
            return (Criteria) this;
        }

        public Criteria andMeanSleepRespirationGreaterThan(Integer value) {
            addCriterion("mean_sleep_respiration >", value, "meanSleepRespiration");
            return (Criteria) this;
        }

        public Criteria andMeanSleepRespirationGreaterThanOrEqualTo(Integer value) {
            addCriterion("mean_sleep_respiration >=", value, "meanSleepRespiration");
            return (Criteria) this;
        }

        public Criteria andMeanSleepRespirationLessThan(Integer value) {
            addCriterion("mean_sleep_respiration <", value, "meanSleepRespiration");
            return (Criteria) this;
        }

        public Criteria andMeanSleepRespirationLessThanOrEqualTo(Integer value) {
            addCriterion("mean_sleep_respiration <=", value, "meanSleepRespiration");
            return (Criteria) this;
        }

        public Criteria andMeanSleepRespirationIn(List<Integer> values) {
            addCriterion("mean_sleep_respiration in", values, "meanSleepRespiration");
            return (Criteria) this;
        }

        public Criteria andMeanSleepRespirationNotIn(List<Integer> values) {
            addCriterion("mean_sleep_respiration not in", values, "meanSleepRespiration");
            return (Criteria) this;
        }

        public Criteria andMeanSleepRespirationBetween(Integer value1, Integer value2) {
            addCriterion("mean_sleep_respiration between", value1, value2, "meanSleepRespiration");
            return (Criteria) this;
        }

        public Criteria andMeanSleepRespirationNotBetween(Integer value1, Integer value2) {
            addCriterion("mean_sleep_respiration not between", value1, value2, "meanSleepRespiration");
            return (Criteria) this;
        }

        public Criteria andSleepMeanHeartbeatIsNull() {
            addCriterion("sleep_mean_heartbeat is null");
            return (Criteria) this;
        }

        public Criteria andSleepMeanHeartbeatIsNotNull() {
            addCriterion("sleep_mean_heartbeat is not null");
            return (Criteria) this;
        }

        public Criteria andSleepMeanHeartbeatEqualTo(Integer value) {
            addCriterion("sleep_mean_heartbeat =", value, "sleepMeanHeartbeat");
            return (Criteria) this;
        }

        public Criteria andSleepMeanHeartbeatNotEqualTo(Integer value) {
            addCriterion("sleep_mean_heartbeat <>", value, "sleepMeanHeartbeat");
            return (Criteria) this;
        }

        public Criteria andSleepMeanHeartbeatGreaterThan(Integer value) {
            addCriterion("sleep_mean_heartbeat >", value, "sleepMeanHeartbeat");
            return (Criteria) this;
        }

        public Criteria andSleepMeanHeartbeatGreaterThanOrEqualTo(Integer value) {
            addCriterion("sleep_mean_heartbeat >=", value, "sleepMeanHeartbeat");
            return (Criteria) this;
        }

        public Criteria andSleepMeanHeartbeatLessThan(Integer value) {
            addCriterion("sleep_mean_heartbeat <", value, "sleepMeanHeartbeat");
            return (Criteria) this;
        }

        public Criteria andSleepMeanHeartbeatLessThanOrEqualTo(Integer value) {
            addCriterion("sleep_mean_heartbeat <=", value, "sleepMeanHeartbeat");
            return (Criteria) this;
        }

        public Criteria andSleepMeanHeartbeatIn(List<Integer> values) {
            addCriterion("sleep_mean_heartbeat in", values, "sleepMeanHeartbeat");
            return (Criteria) this;
        }

        public Criteria andSleepMeanHeartbeatNotIn(List<Integer> values) {
            addCriterion("sleep_mean_heartbeat not in", values, "sleepMeanHeartbeat");
            return (Criteria) this;
        }

        public Criteria andSleepMeanHeartbeatBetween(Integer value1, Integer value2) {
            addCriterion("sleep_mean_heartbeat between", value1, value2, "sleepMeanHeartbeat");
            return (Criteria) this;
        }

        public Criteria andSleepMeanHeartbeatNotBetween(Integer value1, Integer value2) {
            addCriterion("sleep_mean_heartbeat not between", value1, value2, "sleepMeanHeartbeat");
            return (Criteria) this;
        }

        public Criteria andNumberDeparturesBedIsNull() {
            addCriterion("number_departures_bed is null");
            return (Criteria) this;
        }

        public Criteria andNumberDeparturesBedIsNotNull() {
            addCriterion("number_departures_bed is not null");
            return (Criteria) this;
        }

        public Criteria andNumberDeparturesBedEqualTo(Integer value) {
            addCriterion("number_departures_bed =", value, "numberDeparturesBed");
            return (Criteria) this;
        }

        public Criteria andNumberDeparturesBedNotEqualTo(Integer value) {
            addCriterion("number_departures_bed <>", value, "numberDeparturesBed");
            return (Criteria) this;
        }

        public Criteria andNumberDeparturesBedGreaterThan(Integer value) {
            addCriterion("number_departures_bed >", value, "numberDeparturesBed");
            return (Criteria) this;
        }

        public Criteria andNumberDeparturesBedGreaterThanOrEqualTo(Integer value) {
            addCriterion("number_departures_bed >=", value, "numberDeparturesBed");
            return (Criteria) this;
        }

        public Criteria andNumberDeparturesBedLessThan(Integer value) {
            addCriterion("number_departures_bed <", value, "numberDeparturesBed");
            return (Criteria) this;
        }

        public Criteria andNumberDeparturesBedLessThanOrEqualTo(Integer value) {
            addCriterion("number_departures_bed <=", value, "numberDeparturesBed");
            return (Criteria) this;
        }

        public Criteria andNumberDeparturesBedIn(List<Integer> values) {
            addCriterion("number_departures_bed in", values, "numberDeparturesBed");
            return (Criteria) this;
        }

        public Criteria andNumberDeparturesBedNotIn(List<Integer> values) {
            addCriterion("number_departures_bed not in", values, "numberDeparturesBed");
            return (Criteria) this;
        }

        public Criteria andNumberDeparturesBedBetween(Integer value1, Integer value2) {
            addCriterion("number_departures_bed between", value1, value2, "numberDeparturesBed");
            return (Criteria) this;
        }

        public Criteria andNumberDeparturesBedNotBetween(Integer value1, Integer value2) {
            addCriterion("number_departures_bed not between", value1, value2, "numberDeparturesBed");
            return (Criteria) this;
        }

        public Criteria andNumberTurnsIsNull() {
            addCriterion("number_turns is null");
            return (Criteria) this;
        }

        public Criteria andNumberTurnsIsNotNull() {
            addCriterion("number_turns is not null");
            return (Criteria) this;
        }

        public Criteria andNumberTurnsEqualTo(Integer value) {
            addCriterion("number_turns =", value, "numberTurns");
            return (Criteria) this;
        }

        public Criteria andNumberTurnsNotEqualTo(Integer value) {
            addCriterion("number_turns <>", value, "numberTurns");
            return (Criteria) this;
        }

        public Criteria andNumberTurnsGreaterThan(Integer value) {
            addCriterion("number_turns >", value, "numberTurns");
            return (Criteria) this;
        }

        public Criteria andNumberTurnsGreaterThanOrEqualTo(Integer value) {
            addCriterion("number_turns >=", value, "numberTurns");
            return (Criteria) this;
        }

        public Criteria andNumberTurnsLessThan(Integer value) {
            addCriterion("number_turns <", value, "numberTurns");
            return (Criteria) this;
        }

        public Criteria andNumberTurnsLessThanOrEqualTo(Integer value) {
            addCriterion("number_turns <=", value, "numberTurns");
            return (Criteria) this;
        }

        public Criteria andNumberTurnsIn(List<Integer> values) {
            addCriterion("number_turns in", values, "numberTurns");
            return (Criteria) this;
        }

        public Criteria andNumberTurnsNotIn(List<Integer> values) {
            addCriterion("number_turns not in", values, "numberTurns");
            return (Criteria) this;
        }

        public Criteria andNumberTurnsBetween(Integer value1, Integer value2) {
            addCriterion("number_turns between", value1, value2, "numberTurns");
            return (Criteria) this;
        }

        public Criteria andNumberTurnsNotBetween(Integer value1, Integer value2) {
            addCriterion("number_turns not between", value1, value2, "numberTurns");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(Date value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(Date value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(Date value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(Date value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<Date> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<Date> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(Date value1, Date value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNull() {
            addCriterion("updated_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNotNull() {
            addCriterion("updated_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtEqualTo(Date value) {
            addCriterion("updated_at =", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotEqualTo(Date value) {
            addCriterion("updated_at <>", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThan(Date value) {
            addCriterion("updated_at >", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("updated_at >=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThan(Date value) {
            addCriterion("updated_at <", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
            addCriterion("updated_at <=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIn(List<Date> values) {
            addCriterion("updated_at in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotIn(List<Date> values) {
            addCriterion("updated_at not in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtBetween(Date value1, Date value2) {
            addCriterion("updated_at between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
            addCriterion("updated_at not between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andDeletedAtIsNull() {
            addCriterion("deleted_at is null");
            return (Criteria) this;
        }

        public Criteria andDeletedAtIsNotNull() {
            addCriterion("deleted_at is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedAtEqualTo(Date value) {
            addCriterion("deleted_at =", value, "deletedAt");
            return (Criteria) this;
        }

        public Criteria andDeletedAtNotEqualTo(Date value) {
            addCriterion("deleted_at <>", value, "deletedAt");
            return (Criteria) this;
        }

        public Criteria andDeletedAtGreaterThan(Date value) {
            addCriterion("deleted_at >", value, "deletedAt");
            return (Criteria) this;
        }

        public Criteria andDeletedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("deleted_at >=", value, "deletedAt");
            return (Criteria) this;
        }

        public Criteria andDeletedAtLessThan(Date value) {
            addCriterion("deleted_at <", value, "deletedAt");
            return (Criteria) this;
        }

        public Criteria andDeletedAtLessThanOrEqualTo(Date value) {
            addCriterion("deleted_at <=", value, "deletedAt");
            return (Criteria) this;
        }

        public Criteria andDeletedAtIn(List<Date> values) {
            addCriterion("deleted_at in", values, "deletedAt");
            return (Criteria) this;
        }

        public Criteria andDeletedAtNotIn(List<Date> values) {
            addCriterion("deleted_at not in", values, "deletedAt");
            return (Criteria) this;
        }

        public Criteria andDeletedAtBetween(Date value1, Date value2) {
            addCriterion("deleted_at between", value1, value2, "deletedAt");
            return (Criteria) this;
        }

        public Criteria andDeletedAtNotBetween(Date value1, Date value2) {
            addCriterion("deleted_at not between", value1, value2, "deletedAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sleep
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sleep
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}