package com.cz.entity;

import java.util.Date;

public class Sleep {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sleep.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sleep.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sleep.exist
     *
     * @mbg.generated
     */
    private Integer exist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sleep.sleep_status
     *
     * @mbg.generated
     */
    private Integer sleepStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sleep.sleep_score
     *
     * @mbg.generated
     */
    private Integer sleepScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sleep.sleep_quality
     *
     * @mbg.generated
     */
    private Integer sleepQuality;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sleep.total_sleep_duration
     *
     * @mbg.generated
     */
    private Integer totalSleepDuration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sleep.mean_sleep_respiration
     *
     * @mbg.generated
     */
    private Integer meanSleepRespiration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sleep.sleep_mean_heartbeat
     *
     * @mbg.generated
     */
    private Integer sleepMeanHeartbeat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sleep.number_departures_bed
     *
     * @mbg.generated
     */
    private Integer numberDeparturesBed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sleep.number_turns
     *
     * @mbg.generated
     */
    private Integer numberTurns;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sleep.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sleep.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sleep.deleted_at
     *
     * @mbg.generated
     */
    private Date deletedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sleep.id
     *
     * @return the value of sleep.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sleep.id
     *
     * @param id the value for sleep.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sleep.user_id
     *
     * @return the value of sleep.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sleep.user_id
     *
     * @param userId the value for sleep.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sleep.exist
     *
     * @return the value of sleep.exist
     *
     * @mbg.generated
     */
    public Integer getExist() {
        return exist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sleep.exist
     *
     * @param exist the value for sleep.exist
     *
     * @mbg.generated
     */
    public void setExist(Integer exist) {
        this.exist = exist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sleep.sleep_status
     *
     * @return the value of sleep.sleep_status
     *
     * @mbg.generated
     */
    public Integer getSleepStatus() {
        return sleepStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sleep.sleep_status
     *
     * @param sleepStatus the value for sleep.sleep_status
     *
     * @mbg.generated
     */
    public void setSleepStatus(Integer sleepStatus) {
        this.sleepStatus = sleepStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sleep.sleep_score
     *
     * @return the value of sleep.sleep_score
     *
     * @mbg.generated
     */
    public Integer getSleepScore() {
        return sleepScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sleep.sleep_score
     *
     * @param sleepScore the value for sleep.sleep_score
     *
     * @mbg.generated
     */
    public void setSleepScore(Integer sleepScore) {
        this.sleepScore = sleepScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sleep.sleep_quality
     *
     * @return the value of sleep.sleep_quality
     *
     * @mbg.generated
     */
    public Integer getSleepQuality() {
        return sleepQuality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sleep.sleep_quality
     *
     * @param sleepQuality the value for sleep.sleep_quality
     *
     * @mbg.generated
     */
    public void setSleepQuality(Integer sleepQuality) {
        this.sleepQuality = sleepQuality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sleep.total_sleep_duration
     *
     * @return the value of sleep.total_sleep_duration
     *
     * @mbg.generated
     */
    public Integer getTotalSleepDuration() {
        return totalSleepDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sleep.total_sleep_duration
     *
     * @param totalSleepDuration the value for sleep.total_sleep_duration
     *
     * @mbg.generated
     */
    public void setTotalSleepDuration(Integer totalSleepDuration) {
        this.totalSleepDuration = totalSleepDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sleep.mean_sleep_respiration
     *
     * @return the value of sleep.mean_sleep_respiration
     *
     * @mbg.generated
     */
    public Integer getMeanSleepRespiration() {
        return meanSleepRespiration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sleep.mean_sleep_respiration
     *
     * @param meanSleepRespiration the value for sleep.mean_sleep_respiration
     *
     * @mbg.generated
     */
    public void setMeanSleepRespiration(Integer meanSleepRespiration) {
        this.meanSleepRespiration = meanSleepRespiration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sleep.sleep_mean_heartbeat
     *
     * @return the value of sleep.sleep_mean_heartbeat
     *
     * @mbg.generated
     */
    public Integer getSleepMeanHeartbeat() {
        return sleepMeanHeartbeat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sleep.sleep_mean_heartbeat
     *
     * @param sleepMeanHeartbeat the value for sleep.sleep_mean_heartbeat
     *
     * @mbg.generated
     */
    public void setSleepMeanHeartbeat(Integer sleepMeanHeartbeat) {
        this.sleepMeanHeartbeat = sleepMeanHeartbeat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sleep.number_departures_bed
     *
     * @return the value of sleep.number_departures_bed
     *
     * @mbg.generated
     */
    public Integer getNumberDeparturesBed() {
        return numberDeparturesBed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sleep.number_departures_bed
     *
     * @param numberDeparturesBed the value for sleep.number_departures_bed
     *
     * @mbg.generated
     */
    public void setNumberDeparturesBed(Integer numberDeparturesBed) {
        this.numberDeparturesBed = numberDeparturesBed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sleep.number_turns
     *
     * @return the value of sleep.number_turns
     *
     * @mbg.generated
     */
    public Integer getNumberTurns() {
        return numberTurns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sleep.number_turns
     *
     * @param numberTurns the value for sleep.number_turns
     *
     * @mbg.generated
     */
    public void setNumberTurns(Integer numberTurns) {
        this.numberTurns = numberTurns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sleep.created_at
     *
     * @return the value of sleep.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sleep.created_at
     *
     * @param createdAt the value for sleep.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sleep.updated_at
     *
     * @return the value of sleep.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sleep.updated_at
     *
     * @param updatedAt the value for sleep.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sleep.deleted_at
     *
     * @return the value of sleep.deleted_at
     *
     * @mbg.generated
     */
    public Date getDeletedAt() {
        return deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sleep.deleted_at
     *
     * @param deletedAt the value for sleep.deleted_at
     *
     * @mbg.generated
     */
    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }
}