package com.cz.entity;

import java.util.Date;

public class Wardship {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wardship.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wardship.older_id
     *
     * @mbg.generated
     */
    private String olderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wardship.guardian_id
     *
     * @mbg.generated
     */
    private String guardianId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wardship.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wardship.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wardship.deleted_at
     *
     * @mbg.generated
     */
    private Date deletedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wardship.id
     *
     * @return the value of wardship.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wardship.id
     *
     * @param id the value for wardship.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wardship.older_id
     *
     * @return the value of wardship.older_id
     *
     * @mbg.generated
     */
    public String getOlderId() {
        return olderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wardship.older_id
     *
     * @param olderId the value for wardship.older_id
     *
     * @mbg.generated
     */
    public void setOlderId(String olderId) {
        this.olderId = olderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wardship.guardian_id
     *
     * @return the value of wardship.guardian_id
     *
     * @mbg.generated
     */
    public String getGuardianId() {
        return guardianId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wardship.guardian_id
     *
     * @param guardianId the value for wardship.guardian_id
     *
     * @mbg.generated
     */
    public void setGuardianId(String guardianId) {
        this.guardianId = guardianId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wardship.created_at
     *
     * @return the value of wardship.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wardship.created_at
     *
     * @param createdAt the value for wardship.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wardship.updated_at
     *
     * @return the value of wardship.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wardship.updated_at
     *
     * @param updatedAt the value for wardship.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wardship.deleted_at
     *
     * @return the value of wardship.deleted_at
     *
     * @mbg.generated
     */
    public Date getDeletedAt() {
        return deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wardship.deleted_at
     *
     * @param deletedAt the value for wardship.deleted_at
     *
     * @mbg.generated
     */
    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }
}