package com.cz.dao;

import com.cz.entity.ChatItem;
import com.cz.entity.ChatItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChatItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_item
     *
     * @mbg.generated
     */
    long countByExample(ChatItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_item
     *
     * @mbg.generated
     */
    int deleteByExample(ChatItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_item
     *
     * @mbg.generated
     */
    int insert(ChatItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_item
     *
     * @mbg.generated
     */
    int insertSelective(ChatItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_item
     *
     * @mbg.generated
     */
    List<ChatItem> selectByExample(ChatItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_item
     *
     * @mbg.generated
     */
    ChatItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_item
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ChatItem record, @Param("example") ChatItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_item
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ChatItem record, @Param("example") ChatItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ChatItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ChatItem record);
}