package com.cz.dao;

import com.cz.entity.ChatApiKey;
import com.cz.entity.ChatApiKeyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChatApiKeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_api_key
     *
     * @mbg.generated
     */
    long countByExample(ChatApiKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_api_key
     *
     * @mbg.generated
     */
    int deleteByExample(ChatApiKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_api_key
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_api_key
     *
     * @mbg.generated
     */
    int insert(ChatApiKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_api_key
     *
     * @mbg.generated
     */
    int insertSelective(ChatApiKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_api_key
     *
     * @mbg.generated
     */
    List<ChatApiKey> selectByExample(ChatApiKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_api_key
     *
     * @mbg.generated
     */
    ChatApiKey selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_api_key
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ChatApiKey record, @Param("example") ChatApiKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_api_key
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ChatApiKey record, @Param("example") ChatApiKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_api_key
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ChatApiKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_api_key
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ChatApiKey record);
}