package com.cz.dao;

import com.cz.entity.ChatHistory;
import com.cz.entity.ChatHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChatHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_history
     *
     * @mbg.generated
     */
    long countByExample(ChatHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_history
     *
     * @mbg.generated
     */
    int deleteByExample(ChatHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_history
     *
     * @mbg.generated
     */
    int insert(ChatHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_history
     *
     * @mbg.generated
     */
    int insertSelective(ChatHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_history
     *
     * @mbg.generated
     */
    List<ChatHistory> selectByExampleWithBLOBs(ChatHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_history
     *
     * @mbg.generated
     */
    List<ChatHistory> selectByExample(ChatHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_history
     *
     * @mbg.generated
     */
    ChatHistory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ChatHistory record, @Param("example") ChatHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_history
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") ChatHistory record, @Param("example") ChatHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ChatHistory record, @Param("example") ChatHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ChatHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ChatHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ChatHistory record);
}