package com.cz.dao;

import com.cz.entity.ChatModel;
import com.cz.entity.ChatModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChatModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_model
     *
     * @mbg.generated
     */
    long countByExample(ChatModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_model
     *
     * @mbg.generated
     */
    int deleteByExample(ChatModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_model
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_model
     *
     * @mbg.generated
     */
    int insert(ChatModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_model
     *
     * @mbg.generated
     */
    int insertSelective(ChatModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_model
     *
     * @mbg.generated
     */
    List<ChatModel> selectByExample(ChatModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_model
     *
     * @mbg.generated
     */
    ChatModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_model
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ChatModel record, @Param("example") ChatModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_model
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ChatModel record, @Param("example") ChatModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_model
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ChatModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_model
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ChatModel record);
}