package com.cz.dao;

import com.cz.entity.ChatConfig;
import com.cz.entity.ChatConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChatConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_config
     *
     * @mbg.generated
     */
    long countByExample(ChatConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_config
     *
     * @mbg.generated
     */
    int deleteByExample(ChatConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_config
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_config
     *
     * @mbg.generated
     */
    int insert(ChatConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_config
     *
     * @mbg.generated
     */
    int insertSelective(ChatConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_config
     *
     * @mbg.generated
     */
    List<ChatConfig> selectByExampleWithBLOBs(ChatConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_config
     *
     * @mbg.generated
     */
    List<ChatConfig> selectByExample(ChatConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_config
     *
     * @mbg.generated
     */
    ChatConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_config
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ChatConfig record, @Param("example") ChatConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_config
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") ChatConfig record, @Param("example") ChatConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_config
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ChatConfig record, @Param("example") ChatConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ChatConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ChatConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ChatConfig record);
}