package com.cz.dao;

import com.cz.entity.HealthArchive;
import com.cz.entity.HealthArchiveExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HealthArchiveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health_archive
     *
     * @mbg.generated
     */
    long countByExample(HealthArchiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health_archive
     *
     * @mbg.generated
     */
    int deleteByExample(HealthArchiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health_archive
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health_archive
     *
     * @mbg.generated
     */
    int insert(HealthArchive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health_archive
     *
     * @mbg.generated
     */
    int insertSelective(HealthArchive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health_archive
     *
     * @mbg.generated
     */
    List<HealthArchive> selectByExample(HealthArchiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health_archive
     *
     * @mbg.generated
     */
    HealthArchive selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health_archive
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HealthArchive record, @Param("example") HealthArchiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health_archive
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HealthArchive record, @Param("example") HealthArchiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health_archive
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HealthArchive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table health_archive
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HealthArchive record);
}