package com.cz.dao;

import com.cz.entity.Measurement;
import com.cz.entity.MeasurementExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MeasurementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measurement
     *
     * @mbg.generated
     */
    long countByExample(MeasurementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measurement
     *
     * @mbg.generated
     */
    int deleteByExample(MeasurementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measurement
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measurement
     *
     * @mbg.generated
     */
    int insert(Measurement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measurement
     *
     * @mbg.generated
     */
    int insertSelective(Measurement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measurement
     *
     * @mbg.generated
     */
    List<Measurement> selectByExampleWithBLOBs(MeasurementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measurement
     *
     * @mbg.generated
     */
    List<Measurement> selectByExample(MeasurementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measurement
     *
     * @mbg.generated
     */
    Measurement selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measurement
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Measurement record, @Param("example") MeasurementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measurement
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") Measurement record, @Param("example") MeasurementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measurement
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Measurement record, @Param("example") MeasurementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measurement
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Measurement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measurement
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Measurement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table measurement
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Measurement record);
}