package com.cz.dao;

import com.cz.entity.Posture;
import com.cz.entity.PostureExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PostureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posture
     *
     * @mbg.generated
     */
    long countByExample(PostureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posture
     *
     * @mbg.generated
     */
    int deleteByExample(PostureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posture
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posture
     *
     * @mbg.generated
     */
    int insert(Posture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posture
     *
     * @mbg.generated
     */
    int insertSelective(Posture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posture
     *
     * @mbg.generated
     */
    List<Posture> selectByExample(PostureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posture
     *
     * @mbg.generated
     */
    Posture selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posture
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Posture record, @Param("example") PostureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posture
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Posture record, @Param("example") PostureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posture
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Posture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posture
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Posture record);
}