package com.cz.dao;

import com.cz.entity.Wardship;
import com.cz.entity.WardshipExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WardshipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wardship
     *
     * @mbg.generated
     */
    long countByExample(WardshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wardship
     *
     * @mbg.generated
     */
    int deleteByExample(WardshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wardship
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wardship
     *
     * @mbg.generated
     */
    int insert(Wardship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wardship
     *
     * @mbg.generated
     */
    int insertSelective(Wardship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wardship
     *
     * @mbg.generated
     */
    List<Wardship> selectByExample(WardshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wardship
     *
     * @mbg.generated
     */
    Wardship selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wardship
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Wardship record, @Param("example") WardshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wardship
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Wardship record, @Param("example") WardshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wardship
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Wardship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wardship
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Wardship record);
}